<a href="https://colab.research.google.com/github/iamkaiwei/translational_experiment/blob/master/%22HelloWorld%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import json #create the json
import shutil #copy images to train, test and valid dirs
import os #files and dirs manipulation
import math #split calculate

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [ ]:

%matplotlib inline
import matplotlib.pyplot as ply

import os, json
from glob import glob

import keras
import keras.utils
from keras import utils as np_utils
from keras import utils as np_utils
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
#path configuration
parent_dir = '/content/drive/My Drive/Dataset'
path = "/content/drive/My Drive/Dataset/training"
validation_data_dir = "/content/drive/My Drive/Dataset/validation"
test_dir="/content/drive/My Drive/Dataset/test"

In [ ]:
train_batches = ImageDataGenerator().flow_from_directory(path, target_size=(224,224), classes=['n0', 'n1'], batch_size=10)
valid_batches = ImageDataGenerator().flow_from_directory(validation_data_dir, target_size=(224,224), classes=['n0', 'n1'], batch_size=4)

Found 199 images belonging to 2 classes.
Found 38 images belonging to 2 classes.


In [ ]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), strides=(1, 1),
                 activation='relu',
                 input_shape=(224,224,3)))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
# model.add(Dense(1000, activation='relu'))
model.add(Dense(2, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 222, 222, 32)      896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 111, 111, 32)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 109, 109, 64)      18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 54, 54, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 52, 52, 128)       73856     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 26, 26, 128)       0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 86528)            

In [ ]:
from keras.optimizers import Adam
# compiling the sequential model
model.compile(Adam(lr=.0001), loss='categorical_crossentropy', metrics=[tf.keras.metrics.AUC()])


In [ ]:
model.fit_generator(train_batches, steps_per_epoch=4,validation_data=valid_batches
                    ,validation_steps=4, epochs=10,verbose=2)

Epoch 1/10
 - 1s - loss: 1.1921e-08 - auc: 0.8302 - val_loss: 0.0000e+00 - val_auc: 0.8380
Epoch 2/10
 - 0s - loss: 0.0000e+00 - auc: 0.8466 - val_loss: 0.0000e+00 - val_auc: 0.8530
Epoch 3/10
 - 1s - loss: 1.4066e-06 - auc: 0.8601 - val_loss: 1.3226e-04 - val_auc: 0.8652
Epoch 4/10
 - 0s - loss: 2.3662e-04 - auc: 0.8711 - val_loss: 0.0036 - val_auc: 0.8754
Epoch 5/10
 - 0s - loss: 0.0075 - auc: 0.8797 - val_loss: 3.5588e-04 - val_auc: 0.8832
Epoch 6/10
 - 1s - loss: 6.2466e-04 - auc: 0.8873 - val_loss: 2.2717e-04 - val_auc: 0.8908
Epoch 7/10
 - 0s - loss: 9.2510e-05 - auc: 0.8948 - val_loss: 4.7684e-07 - val_auc: 0.8978
Epoch 8/10
 - 0s - loss: 2.6612e-06 - auc: 0.9014 - val_loss: 0.0000e+00 - val_auc: 0.9039
Epoch 9/10
 - 0s - loss: 5.0624e-07 - auc: 0.9069 - val_loss: 2.9802e-08 - val_auc: 0.9093
Epoch 10/10
 - 0s - loss: 4.4703e-08 - auc: 0.9121 - val_loss: 0.0000e+00 - val_auc: 0.9142


In [ ]:
model.save_weights('attempt2.h5')

In [ ]:
test_batches = ImageDataGenerator().flow_from_directory(test_dir, target_size=(224,224), classes=['n0', 'n1'], batch_size=10)

Found 11 images belonging to 2 classes.


In [ ]:
test_imgs, test_labels = next(test_batches)

In [ ]:
test_labels

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [ ]:
predictions = model.predict_generator(test_batches, steps=1, verbose=0)

In [ ]:
predictions

array([[4.9315711e-37, 1.0000000e+00],
       [1.0000000e+00, 4.8669579e-09],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 3.9539194e-13],
       [9.9999988e-01, 7.6981571e-08],
       [3.1685522e-37, 1.0000000e+00],
       [9.9999452e-01, 5.4552788e-06],
       [1.0000000e+00, 1.1108750e-08],
       [6.3231110e-38, 1.0000000e+00]], dtype=float32)

In [ ]:
test2_dir="/content/drive/My Drive/Dataset/test2"

In [ ]:
test2_batches = ImageDataGenerator().flow_from_directory(test2_dir, target_size=(224,224), classes=['n0', 'n1'], batch_size=14)

Found 28 images belonging to 2 classes.


In [ ]:
test2_imgs, test2_labels = next(test2_batches)

In [ ]:
test2_labels

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [ ]:
predictions2 = model.predict_generator(test2_batches, steps=1, verbose=0)

In [ ]:
predictions2

array([[8.87963331e-25, 1.00000000e+00],
       [5.71554857e-16, 1.00000000e+00],
       [3.81349532e-16, 1.00000000e+00],
       [8.49618420e-24, 1.00000000e+00],
       [1.35640247e-23, 1.00000000e+00],
       [6.85660804e-15, 1.00000000e+00],
       [5.68774600e-18, 1.00000000e+00],
       [1.94802530e-16, 1.00000000e+00],
       [9.10708331e-16, 1.00000000e+00],
       [6.86216543e-27, 1.00000000e+00],
       [1.31901532e-16, 1.00000000e+00],
       [3.31026704e-23, 1.00000000e+00],
       [8.09553264e-15, 1.00000000e+00],
       [1.15012714e-17, 1.00000000e+00]], dtype=float32)